# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.4
java_version = 21

# Dependencies
architectury_api_version = 15.0.3

fabric_api_version = 0.119.2+1.21.4
neoforge_version = 21.4.155
parchment = 2025.03.23

modmenu_version = 13.0.3
jade_version_fabric = 17.2.2
jade_version_neoforge = 17.3.0
