# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2
java_version = 25

# Dependencies
architectury_api_version = 20.0.9

fabric_api_version = 0.155.2+26.1.2
neoforge_version = 26.1.2.82

modmenu_version = 18.0.0
jade_version = 26.1.8
