# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1
java_version = 25

# Dependencies
architectury_api_version = 20.0.4

fabric_api_version = 0.145.1+26.1
neoforge_version = 26.1.0.19-beta

modmenu_version = 18.0.0

