# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2
java_version = 25

# Dependencies
architectury_api_version = 21.0.4

fabric_api_version = 0.155.2+26.2
neoforge_version = 26.2.0.25-beta

modmenu_version = 20.0.1
jade_version_fabric = 26.2.9
jade_version_neoforge = 26.2.8
