plugins {
    id 'com.gradleup.shadow' version '8.3.6'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        name 'Xander Maven'
        url 'https://maven.isxander.dev/releases'
    }
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

int version_index = Integer.valueOf(rootProject.index)

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

    def impl_type = (version_index < 18) ? "modImplementation" : "implementation"

    add impl_type, "dev.architectury:architectury-neoforge:${rootProject.architectury_api_version}"
    add impl_type, "maven.modrinth:jade:${(rootProject.hasProperty("jade_version_neoforge")) ? rootProject.jade_version_neoforge : rootProject.jade_version}${(version_index < 5 || version_index == 6) ? "" : "+neoforge"}"

    if (version_index < 18)
        common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    else
        common(project(path: ':common')) { transitive false }


    shadowBundle(project(path: ':common', configuration: 'transformProductionNeoForge'))
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

if (version_index < 18) {
    remapJar {
        inputFile.set shadowJar.archiveFile
    }
} else {
    jar {
        archiveClassifier.set("dev")
    }
    shadowJar {
        archiveClassifier.set("")
    }
    assemble {
        dependsOn("shadowJar")
    }
}


